//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABAJADORES
    {
        public int DNI { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public string NOMBRES { get; set; }
        public int SUELDO { get; set; }
        public string CODA { get; set; }
    }
}
